
class HomeKeys:
    FOR_SALE_ID = "x"
    ID_KEY = "id"
    ADDRESS_KEY = "address"
    PRICE_KEY = "price"
    SQ_FT_KEY = "sq_ft"
    BEDS_KEY = "beds"
    BATHS_KEY = "baths"
    POOL_KEY = "pool"
    REMOD_SCORE_KEY = "subj_remodel_score"
    THROW_OUT_KEY = "throw_out"
    FOR_SALE_KEY = "for_sale"
    SOLD_PRICE_KEY = "sold_price"
    SOLD_DATE_KEY = "sold_date"
    LOT_SIZE_KEY = "lot_size"
    LIST_PRICE_KEY = "list_price"

    PPSF_KEY = "price_per_sq_foot"
    PPSF_RANK_KEY = "price_per_sq_foot_rank"
    NA = "NA"